### ISSUE TITLE
Error when debug main.py

### ISSUE THREAD

**Issue by geeks121** [Pycomet/escrow-service-bot#2]
```
Connected to pydev debugger (build 201.7223.92)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\HP ProBook 4530s\Documents\escrow-service-bot\config.py", line 24, in <module>
    importdir.do("handlers", globals())
  File "C:\Users\HP ProBook 4530s\Documents\escrow-service-bot\importdir.py", line 18, in do
    __do(path, env)
  File "C:\Users\HP ProBook 4530s\Documents\escrow-service-bot\importdir.py", line 47, in __do
    env[module_name] = __import__(module_name)              # ... import
  File "handlers\callbacks.py", line 3, in <module>
    from functions import *
  File "C:\Users\HP ProBook 4530s\Documents\escrow-service-bot\functions.py", line 2, in <module>
    from model import User, Trade, Dispute, Affiliate, session
  File "C:\Users\HP ProBook 4530s\Documents\escrow-service-bot\model.py", line 10, in <module>
    engine = create_engine(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\engine\__init__.py", line 488, in create_engine
    return strategy.create(*args, **kwargs)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sqlalchemy\engine\strategies.py", line 56, in create
    plugins = u._instantiate_plugins(kwargs)
AttributeError: 'NoneType' object has no attribute '_instantiate_plugins'

```

**Comment by Pycomet** [comment]
This error is a result of the debugger not being able to access any DATABASE_URL in your environment variables. And as a result of that, returns 'NoneType' when attempting to create a database engine in models.py on line 10

I suggest you create a .env file to house your environment variables to successfully run the escrow bot service locally with your own credentials. 

You can use this tutorial - https://able.bio/rhett/how-to-set-and-get-environment-variables-in-python--274rgt5#:~:text=To%20set%20and%20get%20environment%20variables%20in%20Python%20you%20can,Get%20environment%20variables%20USER%20%3D%20os.

Good luck!

**Comment by geeks121** [comment]
thank you for giving me solution,, i have try in env ,, but the link you given i'll try now

**Comment by geeks121** [comment]
may you add documentation how to run this script ,, like blog post ,, step by step ,, sory for many request

**Comment by Pycomet** [comment]
What do you think of the README.md? I look forward to writing on how to use this service real soon
