### ISSUE TITLE
Bug when submit trade id at buyer 

### ISSUE THREAD

**Issue by geeks121** [Pycomet/escrow-service-bot#9]
here is log when submet trade id in buyer section : 

2020-07-07 12:02:29,320 (util.py:66 WorkerThread2) ERROR - TeleBot: "NotFoundError occurred, args=(<Response [404]>, 'not_found', 'Not found', [{'id': 'not_found', 'message': 'Not found'}])
Traceback (most recent call last):
  File "/home/ozhy/bot/EscrowService-Bot/env/lib/python3.6/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "handlers/join.py", line 53, in join_trade
    receive_wallet = get_receive_address(trade)
  File "/home/ozhy/bot/EscrowService-Bot/functions.py", line 217, in get_receive_address
    wallet = btc_account.get_address(trade.receive_address_id).address
  File "/home/ozhy/bot/EscrowService-Bot/env/lib/python3.6/site-packages/coinbase/wallet/model.py", line 156, in get_address
    return self.api_client.get_address(self.id, address_id, **params)
  File "/home/ozhy/bot/EscrowService-Bot/env/lib/python3.6/site-packages/coinbase/wallet/client.py", line 291, in get_address
    'v2', 'accounts', account_id, 'addresses', address_id, params=params)
  File "/home/ozhy/bot/EscrowService-Bot/env/lib/python3.6/site-packages/coinbase/wallet/client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "/home/ozhy/bot/EscrowService-Bot/env/lib/python3.6/site-packages/coinbase/wallet/client.py", line 116, in _request
    return self._handle_response(response)
  File "/home/ozhy/bot/EscrowService-Bot/env/lib/python3.6/site-packages/coinbase/wallet/client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found

bot not respon in telegram after submit the trade id ,, this also facing in your bot "escrow service"

**Comment by Pycomet** [comment]
The bug was with the user schema. It saved the corresponding wallet address directly into the schema where it was supposed to put in the wallet address identifier instead.

**Comment by geeks121** [comment]
> /home/ozhy/bot/bot1/escrow-service-bot/functions.py(218)get_receive_address()
-> if trade.coin == "BTC":

after submit trade id ,, bot respond it ,, and not receive any address to pay

**Comment by Pycomet** [comment]
It was undergoing build. The bot is resilient and active
